2022-03-06 10:54:06,067 - config.doExcel - INFO - 开始获取[elementDate.xlsx]的[elementsInfo]表
2022-03-06 10:54:06,114 - config.doExcel - INFO - 开始获取[elementDate.xlsx]的[loginData]表
2022-03-06 10:54:06,114 - config.doExcel - INFO - 创建表[loginData]的数据字典
2022-03-06 10:54:07,390 - common.myUnit - INFO - 打开浏览器
2022-03-06 10:54:07,390 - common.myUnit - INFO - ************************ 开始执行测试用例 ************************
2022-03-06 10:54:09,562 - pageObject.basePage - ERROR - Message: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=99.0.4844.51)
Traceback (most recent call last):
  File "D:\Software\PycharmProjects\sccProjects\pageObject\basePage.py", line 34, in _open
    self.driver.get(url)
  File "D:\Software\python\Anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "D:\Software\python\Anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Software\python\Anaconda\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=99.0.4844.51)

2022-03-06 10:54:10,269 - common.myUnit - INFO - ************************ 测试用例执行结束 ************************
2022-03-06 10:54:10,269 - common.myUnit - INFO - ************************ 开始执行测试用例 ************************
2022-03-06 10:54:13,102 - pageObject.basePage - ERROR - Message: unknown error: cannot determine loading status
from disconnected: received Inspector.detached event
  (Session info: chrome=99.0.4844.51)
Traceback (most recent call last):
  File "D:\Software\PycharmProjects\sccProjects\pageObject\basePage.py", line 34, in _open
    self.driver.get(url)
  File "D:\Software\python\Anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "D:\Software\python\Anaconda\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Software\python\Anaconda\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from disconnected: received Inspector.detached event
  (Session info: chrome=99.0.4844.51)

2022-03-06 10:54:13,817 - common.myUnit - INFO - ************************ 测试用例执行结束 ************************
