2022-03-26 19:04:29,419 - config.doExcel - ERROR - doExcel -21 - 获取工作表[auditCourseData]失败
Traceback (most recent call last):
  File "D:\Software\python\Anaconda\lib\site-packages\xlrd\book.py", line 474, in sheet_by_name
    sheetx = self._sheet_names.index(sheet_name)
ValueError: 'auditCourseData' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Software\PycharmProjects\sccProjects\config\doExcel.py", line 18, in __init__
    self.sheetName = self.workBook.sheet_by_name(sheetName) #获取名字为sheetName的工作表
  File "D:\Software\python\Anaconda\lib\site-packages\xlrd\book.py", line 476, in sheet_by_name
    raise XLRDError('No sheet named <%r>' % sheet_name)
xlrd.biffh.XLRDError: No sheet named <'auditCourseData'>
